include(`../M4/FIRST.M4')dnl
ORG 0x8000
INIT(60000)
define({USE_FONT_5x8})

CONSTANT(BYTES_SIZE,18)
PCONSTANT(BYTES_SIZE,10,_10)
PCONSTANT(BYTES_SIZE,99,_99)
PCONSTANT(BYTES_SIZE,0, _tmp_print)
PCONSTANT(BYTES_SIZE,0, _tmp2)
PPUSH_VALUE(BYTES_SIZE,1,_tmp3)

PUSH(_99)
PUSH(_tmp3)
PUSH(_tmp2)

PUSH(19) FOR
   PUMUL(BYTES_SIZE)
   _2DUP SWAP PUSH(BYTES_SIZE/2) MOVE
   DEC_PUDOT(BYTES_SIZE,_10,_tmp_print) CR
NEXT
 
DROP DROP DROP
PRINT_Z({"Depth: "}) DEPTH UDOT CR

STOP
