include(`./FIRST.M4')dnl 
ORG 0x8000
INIT(60000)
PRINT({"enter 1million or 32million", 0xD})
SCALL(_1million)
STOP

;( Forth nesting (NEXT) Benchmark     cas20101204 )
SCOLON(bottom) SSEMICOLON    
SCOLON(_1st)  SCALL(bottom) SCALL(bottom) SSEMICOLON   SCOLON(_2nd)  SCALL(_1st)  SCALL(_1st)  SSEMICOLON   SCOLON(_3rd)  SCALL(_2nd)  SCALL(_2nd)  SSEMICOLON
SCOLON(_4th)  SCALL(_3rd)   SCALL(_3rd)   SSEMICOLON   SCOLON(_5th)  SCALL(_4th)  SCALL(_4th)  SSEMICOLON   SCOLON(_6th)  SCALL(_5th)  SCALL(_5th)  SSEMICOLON
SCOLON(_7th)  SCALL(_6th)   SCALL(_6th)   SSEMICOLON   SCOLON(_8th)  SCALL(_7th)  SCALL(_7th)  SSEMICOLON   SCOLON(_9th)  SCALL(_8th)  SCALL(_8th)  SSEMICOLON
SCOLON(_10th) SCALL(_9th)   SCALL(_9th)   SSEMICOLON   SCOLON(_11th) SCALL(_10th) SCALL(_10th) SSEMICOLON   SCOLON(_12th) SCALL(_11th) SCALL(_11th) SSEMICOLON
SCOLON(_13th) SCALL(_12th)  SCALL(_12th)  SSEMICOLON   SCOLON(_14th) SCALL(_13th) SCALL(_13th) SSEMICOLON   SCOLON(_15th) SCALL(_14th) SCALL(_14th) SSEMICOLON
SCOLON(_16th) SCALL(_15th)  SCALL(_15th)  SSEMICOLON   SCOLON(_17th) SCALL(_16th) SCALL(_16th) SSEMICOLON   SCOLON(_18th) SCALL(_17th) SCALL(_17th) SSEMICOLON
SCOLON(_19th) SCALL(_18th)  SCALL(_18th)  SSEMICOLON   SCOLON(_20th) SCALL(_19th) SCALL(_19th) SSEMICOLON   SCOLON(_21th) SCALL(_20th) SCALL(_20th) SSEMICOLON
SCOLON(_22th) SCALL(_21th)  SCALL(_21th)  SSEMICOLON   SCOLON(_23th) SCALL(_22th) SCALL(_22th) SSEMICOLON   SCOLON(_24th) SCALL(_23th) SCALL(_23th) SSEMICOLON
SCOLON(_25th) SCALL(_24th)  SCALL(_24th)  SSEMICOLON            

SCOLON(_32million)  PRINT({"32 million nest/unnest operations", 0xD}) SCALL(_25th) SSEMICOLON
SCOLON(_1million)   PRINT({" 1 million nest/unnest operations", 0xD}) SCALL(_20th) SSEMICOLON

include({./LAST.M4})dnl
