; vvvv
include(`./FIRST.M4')dnl
; ^^^^
    ORG 32768
    
    ld  hl, stack_test
    push hl
    INIT(60000)
    
    PUSH2(4, 0)  DO  I PUSH(0)  DO  J DOT  I DOT  LOOP PUTCHAR({','})  LOOP CR
    PUSH2(4, 0) SDO SI PUSH(0) SDO SJ DOT SI DOT SLOOP PUTCHAR({','}) SLOOP CR
      XDO(4, 0)     XI PUSH(0) SDO XI DOT SI DOT SLOOP PUTCHAR({','}) XLOOP CR
    PUSH2(3, 0) SDO SI         FOR SI DOT  I DOT  NEXT PUTCHAR({','}) SLOOP CR
    PUSH2(3, 0)  DO  I        SFOR  I DOT SI DOT SNEXT PUTCHAR({','})  LOOP CR
    
    PUSH(5)   SFOR       SI DOT PUTCHAR({','})    SNEXT CR
    PUSH(5)    FOR        I DOT PUTCHAR({','})     NEXT CR
   
    PRINT("Exit:")
    PUSH2(0,0) DO PUTCHAR('a') LOOP 
    PUSH2(0,1) DO PUTCHAR('b') LOOP 
    XDO(0,0)      PUTCHAR('c') XLOOP 
    XDO(254,254)  PUTCHAR('d') XLOOP 
    XDO(255,255)  PUTCHAR('e') XLOOP 
    XDO(256,256)  PUTCHAR('f') XLOOP
    PUSH2(0,0)     SDO PUTCHAR('g') SLOOP 
    PUSH2(254,254) SDO PUTCHAR('h') SLOOP 
    PUSH2(255,255) SDO PUTCHAR('i') SLOOP 
    PUSH2(256,256) SDO PUTCHAR('j') SLOOP
    XDO(60000,60000) PUTCHAR('k') XADDLOOP(5000)
    XDO(60000,60000) PUTCHAR('l') XADDLOOP(3100)
    
    PRINT({0xD, "Leave >= 7", 0xD})
    PUSH2(12,3)  DO  I DUP_DOT PUSH(7) GE IF LEAVE THEN  LOOP CR
    PUSH2(12,3) SDO SI DUP_DOT PUSH(7) GE IF LEAVE THEN SLOOP CR
    XDO(12,3)  XI DUP_DOT PUSH(7) GE IF LEAVE THEN XLOOP CR
    XDO(550,3) XI DUP_DOT PUSH(7) GE IF LEAVE THEN XLOOP CR
    XDO(12,3)  XI DUP_DOT PUSH(7) GE IF LEAVE THEN XADDLOOP(2) CR
    XDO(550,3) XI DUP_DOT PUSH(7) GE IF LEAVE THEN XADDLOOP(2) CR
    PUSH(12)  FOR  I DUP_DOT PUSH(7) LE IF LEAVE THEN  NEXT CR
    PUSH(12) SFOR SI DUP_DOT PUSH(7) LE IF LEAVE THEN SNEXT CR

    PRINT("Once:")
    PUSH2(1,0) DO PUTCHAR('a') LOOP 
    PUSH2(255,254) DO PUTCHAR('b') LOOP 
    XDO(1,0)      PUTCHAR('c') XLOOP 
    XDO(255,254)  PUTCHAR('d') XLOOP 
    XDO(256,255)  PUTCHAR('e') XLOOP 
    XDO(257,256)  PUTCHAR('f') XLOOP
    PUSH2(1,0)     SDO PUTCHAR('g') SLOOP 
    PUSH2(255,254) SDO PUTCHAR('h') SLOOP 
    PUSH2(256,255) SDO PUTCHAR('i') SLOOP 
    PUSH2(257,256) SDO PUTCHAR('j') SLOOP
    XDO(60000,30000) PUTCHAR('k') XADDLOOP(40000)
    XDO(60000,30000) PUTCHAR('l') XADDLOOP(31000)
    CR
    
    PRINT({"RAS:"})
    exx
    push HL
    exx
    pop HL
    DUP_UDOT
    STOP
    
SCOLON(stack_test)
    PRINT({0xD, "Data stack OK!", 0xD})    
SSEMICOLON
    
    
include({./LAST.M4})dnl
