include(`../M4/FIRST.M4')dnl
    ORG 0x8000
    INIT(60000)
        
    DVARIABLE(A_32,0x87432110)

    PRINT({"  unsigned 4287312975 = signed   -7654321", 0x0D}) 
    PUSHDOT(-7654321) 
       _2DUP DDOT PUTCHAR('=') _2DUP UDDOT CR
       PRINT({"test ABS: "}) DABS _2DUP DDOT CR
       PRINT({"test ABS: "}) DABS 
    DDOT CR
    
    SCALL(Check_stack)
    PRINT({"  number: "}) 
    PUSHDOT(0x0000FFFE)
      _2DUP DDOT CR
      PRINT({"test D1+: "}) D1ADD _2DUP DDOT CR
      PRINT({"test D1+: "}) D1ADD _2DUP DDOT CR
      PRINT({"test D1+: "}) D1ADD _2DUP DDOT CR
      PRINT({"test D1-: "}) D1SUB _2DUP DDOT CR
      PRINT({"test D1-: "}) D1SUB _2DUP DDOT CR
      PRINT({"test D1-: "}) D1SUB 
    DDOT CR    

    SCALL(Check_stack)
    PRINT({"  number: "}) 
    PUSHDOT(0xFFFFFFFE)
      _2DUP DDOT CR
      PRINT({"test D1+: "}) D1ADD _2DUP DDOT CR
      PRINT({"test D1+: "}) D1ADD _2DUP DDOT CR
      PRINT({"test D1+: "}) D1ADD _2DUP DDOT CR
      PRINT({"test D1-: "}) D1SUB _2DUP DDOT CR
      PRINT({"test D1-: "}) D1SUB _2DUP DDOT CR
      PRINT({"test D1-: "}) D1SUB 
    DDOT CR    
    
    SCALL(Check_stack)
    PRINT({"test D+:"})
    PUSHDOT(0) 
           _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT PUTCHAR('+') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DADD _2DUP UDDOT CR
      PRINT({"test D-:"})
           _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB _2DUP UDDOT PUTCHAR('-') PUSHDOT(111111111) _2DUP UDDOT  PUTCHAR('=') CR
      DSUB 
    UDDOT CR
    SCALL(Check_stack)
    
    PRINT({"test dmin, dmax, dnegate", 0x0D})
    PUSHDOT(0x00010002)
    PUSHDOT(0x00010001)
    _4DUP
     _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP DNEGATE
    _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP
    _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP DNEGATE
    _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _4DUP DNEGATE
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP DNEGATE
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _2DROP _2DROP
    SCALL(Check_stack)

    PRINT({"test dmin, dmax, dnegate", 0x0D})
    PUSHDOT(500000)
    PUSHDOT(100000)
    _4DUP
     _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP DNEGATE
    _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP
    _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP DNEGATE
    _4DUP DDOT SPACE_DDOT DMIN PRINT_Z({" min"}) DDOT CR
    _4DUP
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _4DUP DNEGATE
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _4DUP _2SWAP DNEGATE _2SWAP DNEGATE
    _4DUP DDOT SPACE_DDOT DMAX PRINT_Z({" max"}) DDOT CR
    _2DROP _2DROP
    SCALL(Check_stack)

    __RAS
    PRINT_Z({"RAS: "}) UDOT CR

    SCALL(Check_stack)
    STOP
    
COLON(Check_stack)
    DEPTH DOT 
    PRINT_Z({" values in data stack", 0x0D})
SEMICOLON
